/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orthodent.agenda;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import modelo.Usuario;
import orthodent.Item;
import orthodent.db.Autenticacion;

/**
 *
 * @author Lucy
 */
public class BarraAcciones extends javax.swing.JPanel {

    /**
     * Creates new form BarraAcciones
     */
    public BarraAcciones() {
        initComponents();
        initProfesionales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil4 = new org.jdatepicker.util.JDatePickerUtil();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        profesionales = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        profesionales.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        profesionales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Profesional");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(profesionales, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox profesionales;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    // End of variables declaration//GEN-END:variables

    private void initProfesionales() {
        ArrayList<Usuario> usuarios = Autenticacion.listarProfesionales();
            
        if(usuarios!=null && usuarios.size()>0){
            /*Usuario profesional1 = Autenticacion.getUsuario(presupuestoSelected.getIdProfesional());

            //String nombre = profesional1.getNombre();

            if(nombre.contains(" ")){
                nombre = nombre.substring(0,nombre.indexOf(" "));
            }
            //profesionalSelected = nombre+" "+profesional1.getApellido_pat();
            */
            Vector model = new Vector();
            Item item = null;
            int i = 0;
            for(Usuario user : usuarios){
                String name = user.getNombre();

                if(name.contains(" ")){
                    name = name.substring(0,name.indexOf(" "));
                }
                name = name + " " + user.getApellido_pat();
                model.addElement(new Item(name,user.getId_usuario()));
                i++;
            }
            profesionales.setModel(new DefaultComboBoxModel(model));
            profesionales.setSelectedItem(item);
        }

        
        
    }
}
