/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package orthodent;

import java.awt.*;
import orthodent.db.Autenticacion;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import modelo.Usuario;
import orthodent.db.VentanaConfiguracionDB;

/**
 *
 * @author Mary
 */
public class Login extends javax.swing.JDialog implements WindowListener{

    private boolean dialog2;
    
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.dialog2 = false;
        initComponents();
        this.setCursor();
        
        this.setBackground(Color.white);
        this.addWindowListener(this);
        
        this.centrarVentana();
    }
    
    private void setCursor(){
        this.botonAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.botonCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.botonOlvidoContraseña.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void centrarVentana(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width - this.getSize().width) / 2 ,
                (screenSize.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orthodentImagen = new javax.swing.JButton();
        diente1Imagen = new javax.swing.JButton();
        nombreUsuario = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        contraseña = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JPasswordField();
        diente2Imagen = new javax.swing.JButton();
        botonOlvidoContraseña = new javax.swing.JButton();
        botonOlvidoContraseña1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orthondent Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(9, 133, 179));

        orthodentImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orthodent.png"))); // NOI18N
        orthodentImagen.setBorder(null);
        orthodentImagen.setBorderPainted(false);
        orthodentImagen.setContentAreaFilled(false);

        diente1Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diente_mini.png"))); // NOI18N
        diente1Imagen.setBorder(null);
        diente1Imagen.setBorderPainted(false);
        diente1Imagen.setContentAreaFilled(false);

        nombreUsuario.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("Email");

        campoNombreUsuario.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        campoNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNombreUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreUsuarioKeyReleased(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");

        campoContraseña.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        campoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoContraseñaKeyPressed(evt);
            }
        });

        diente2Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diente2_mini.png"))); // NOI18N
        diente2Imagen.setBorder(null);
        diente2Imagen.setBorderPainted(false);
        diente2Imagen.setContentAreaFilled(false);

        botonOlvidoContraseña.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        botonOlvidoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        botonOlvidoContraseña.setText("Olvido contraseña?");
        botonOlvidoContraseña.setBorder(null);
        botonOlvidoContraseña.setBorderPainted(false);
        botonOlvidoContraseña.setContentAreaFilled(false);
        botonOlvidoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOlvidoContraseñaActionPerformed(evt);
            }
        });

        botonOlvidoContraseña1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        botonOlvidoContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        botonOlvidoContraseña1.setText("Configurar DB");
        botonOlvidoContraseña1.setBorder(null);
        botonOlvidoContraseña1.setBorderPainted(false);
        botonOlvidoContraseña1.setContentAreaFilled(false);
        botonOlvidoContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOlvidoContraseña1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(diente2Imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOlvidoContraseña1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(orthodentImagen))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(botonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(botonAceptar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(diente1Imagen))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(botonOlvidoContraseña))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreUsuario)
                                    .addComponent(contraseña))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(campoContraseña))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(orthodentImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(diente1Imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreUsuario)
                            .addComponent(campoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonOlvidoContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAceptar)
                            .addComponent(botonCancelar))
                        .addGap(18, 18, 18)
                        .addComponent(diente2Imagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonOlvidoContraseña1)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
        String nombreUsuario = this.campoNombreUsuario.getText();
        String contraseña = this.campoContraseña.getText();
                
        Usuario usuario = null;
        
        try {
            usuario = Autenticacion.logIn(nombreUsuario, contraseña);
        } catch (Exception ex) {
            usuario = null;
        }
        
        if(usuario!=null){
            this.dispose();
            JVentana ventana = new JVentana(usuario);
            ventana.setVisible(true);
        }
        else{
            this.dialog2 = true;
            JOptionPane.showMessageDialog(this,
                    "El nombre de usuario o contraseña no coinciden",
                    "Orthodent",
                    JOptionPane.ERROR_MESSAGE);
            this.dialog2 = false;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonOlvidoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOlvidoContraseñaActionPerformed
        //Aqui hacer la llamada para cambiar la contraseña
        String correo = (String) JOptionPane.showInputDialog(this,"\nIngrese su correo: \n",
                "Orthodent",
                JOptionPane.PLAIN_MESSAGE,null,null,"");
        
        if(correo!=null && correo.length()>0){
            if(!validarEmail(correo)){
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar un correo válido.");
                return;
            }
            boolean respuesta;
            try {
                respuesta = Autenticacion.recuperarContrasena(correo);
            } catch (Exception ex) {
                respuesta = false;
            }
            
            if(respuesta){
                JOptionPane.showMessageDialog(this,
                        "La nueva contraseña se ha enviado a su correo.");
            }
            else{
                JOptionPane.showMessageDialog(this,
                        "El correo no coincide con ningún registro.");
            }
        }
        if(correo.equals("")){
            JOptionPane.showMessageDialog(this,
                        "Debe ingresar un correo válido.");
        }
    }//GEN-LAST:event_botonOlvidoContraseñaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoNombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !dialog2) {
            botonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_campoNombreUsuarioKeyPressed

    private void campoContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !dialog2) {
            botonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_campoContraseñaKeyPressed

    private void campoNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreUsuarioKeyReleased
        
    }//GEN-LAST:event_campoNombreUsuarioKeyReleased

    private void botonOlvidoContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOlvidoContraseña1ActionPerformed
    JPasswordField pf = new JPasswordField();
    int okCxl = JOptionPane.showConfirmDialog(null, pf, "Ingrese Contraseña Admin BD", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (okCxl == JOptionPane.OK_OPTION) {
      String password = new String(pf.getPassword());
      String pass = "bdorthodent123";
      if(pass.equals(password)){
            VentanaConfiguracionDB v = new VentanaConfiguracionDB(null, true);
      }
      else{
            JOptionPane.showMessageDialog(this,
                    "La contraseña ingresada es incorrecta.",
                    "Orthodent",
                    JOptionPane.INFORMATION_MESSAGE);
      }
    }        
        
    }//GEN-LAST:event_botonOlvidoContraseña1ActionPerformed
    
    
    public static boolean validarEmail(String email) {
        final String PATTERN_EMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        // Compiles the given regular expression into a pattern.
        Pattern pattern = Pattern.compile(PATTERN_EMAIL);
 
        // Match the given input against this pattern
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonOlvidoContraseña;
    private javax.swing.JButton botonOlvidoContraseña1;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton diente1Imagen;
    private javax.swing.JButton diente2Imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JButton orthodentImagen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        System.exit(0);
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
